"""empty message

Revision ID: ef481ed99b2a
Revises: 9d28b652c71b
Create Date: 2023-05-05 22:55:28.531354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef481ed99b2a'
down_revision = '9d28b652c71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('black_coffee_price', sa.String(length=250), nullable=True))
        batch_op.drop_column('coffee_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coffee_price', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('black_coffee_price')

    # ### end Alembic commands ###
